
trigger:
- main

variables:
  appName: 'webapp'

stages:
- stage: Alpha
  jobs:
  - job: CICD
    displayName: 'Build, Test, and Deploy Website'
    workspace:
      clean: outputs | resources | all
    pool: Default
    #  vmImage: 'windows-latest'
    steps:
      - task: PowerShell@2
        displayName: 'Set Build Target'
        inputs:
          targetType: 'inline'
          script: |
            rustup target add wasm32-unknown-unknown
      - task: PowerShell@2
        displayName: 'Run Tests'
        inputs:
          targetType: 'inline'
          script: |
            $test_results = cargo test --release | Out-String

            if ($test_results.Contains("test result: FAILED")) {
              throw "Tests Failed"
            }
      - task: PowerShell@2
        displayName: 'Install Trunk'
        inputs:
          targetType: 'inline'
          script: |
            cargo install trunk
      - task: PowerShell@2
        displayName: 'Install Post Build'
        inputs:
          targetType: 'inline'
          script: |
            cargo install webapp_post_build --git https://github.com/StoicDreams/RustWebUI
      - task: PowerShell@2
        displayName: 'Build Web App'
        inputs:
          targetType: 'inline'
          script: |
            # Change directory to project folder
            cd $(appName)

            # Build
            trunk build --release
      - task: AzureCLI@2
        displayName: 'Remove Old Files'
        inputs:
          azureSubscription: '$(azureSubscription)'
          scriptType: pscore
          scriptLocation: inlineScript
          inlineScript: 'az storage blob delete-batch -s ''$web'' --account-name $(accountName)'
      - task: AzureCLI@2
        displayName: 'Copy Files to Azure Blob Storage'
        inputs:
          azureSubscription: '$(azureSubscription)'
          scriptType: pscore
          scriptLocation: inlineScript
          inlineScript: |
            $Container = '$web'
            az storage copy -s '$(System.DefaultWorkingDirectory)/$(appName)/dist/*' --destination-account-name $(accountName) --destination-container $Container --recursive
      - task: AzureCLI@2
        displayName: 'Set Correct Content-Type Attributes'
        inputs:
          azureSubscription: '$(azureSubscription)'
          scriptType: pscore
          scriptLocation: inlineScript
          inlineScript: |
            $myloc = "$((Get-Location).ProviderPath)\$(appName)\dist\"
            Get-ChildItem "$(appName)/dist" -Filter "*.wasm" -Recurse -Force | ForEach-Object {
                $rel_Path = $_.FullName.Replace($myloc, "")
                az storage blob update -c '$web' -n $rel_Path --account-name $(accountName) --content-type application/wasm
            }
      - task: AzureCLI@2
        displayName: 'Purge Storage Cache'
        inputs:
          azureSubscription: $(azureConnection)
          scriptType: pscore
          scriptLocation: inlineScript
          inlineScript: 'az cdn endpoint purge -g $(resourceGroup) -n $(accountName) --profile-name $(profileName) --content-paths ''/*'''
